/* eslint-disable import/no-anonymous-default-export */
export default {
    URL_BASE: process.env.URL_BASE,
    URL_LOGIN: process.env.URL_LOGIN,
    URL_USUARIO: process.env.URL_USUARIO,
    URL_MODALIDADVALIDACION: process.env.URL_MODALIDADVALIDACION,
    URL_TIPOUSUARIO: process.env.URL_TIPOUSUARIO,
    URL_TIPOJORNADA: process.env.URL_TIPOJORNADA,
    URL_TIPOIMPORTACION: process.env.URL_TIPOIMPORTACION,
    URL_TIPOEMPLEADO: process.env.URL_TIPOEMPLEADO,
    URL_TIPOAUSENCIA: process.env.URL_TIPOAUSENCIA,
    URL_PROYECTO: process.env.URL_PROYECTO,
    URL_JORNADA: process.env.URL_JORNADA,
    URL_EMPLEADO: process.env.URL_EMPLEADO,
    URL_OBSERVACION: process.env.URL_OBSERVACION,
    URL_MODALIDADTRABAJO: process.env.URL_MODALIDADTRABAJO,
    URL_MES: process.env.URL_MES,
    URL_IMPORTACION: process.env.URL_IMPORTACION,
    URL_CONTROL: process.env.URL_CONTROL,
    URL_IMPORTAR: process.env.URL_IMPORTAR,
    URL_EXPORTAR: process.env.URL_EXPORTAR,
    URL_ASISTENCIA: process.env.URL_ASISTENCIA,
    URL_SYNC: process.env.URL_SYNC,
};